djangome/urls.py
from django.conf import settings
from django.conf.urls import *
from django.views.generic import RedirectView

ALL_VERSIONS_RE = '(?P<version>%s)' % '|'.join(settings.DJANGOME['VERSIONS'])

urlpatterns = patterns('',
    url('^$',
        RedirectView.as_view(url='http://docs.djangoproject.com/en/dev/')
    ),
    url('^t(?P<n>\d+)$',
        RedirectView.as_view(url='http://code.djangoproject.com/ticket/%(n)s')
    ),
    url('^r(?P<n>\d+)$',
        RedirectView.as_view(url='http://code.djangoproject.com/changeset/%(n)s')
    ),
    url('^__oneoffs__$',
        'djangome.views.manage_oneoffs',
        name = "manage_oneoffs",
    ),
    url('^(?P<term>[\w\-\.]+)$',
        'djangome.views.redirect_to_term',
        {'version': settings.DJANGOME['DEFAULT_VERSION']},
    ),
    url('^(?P<term>[\w\-\.]+)/stats$',
        'djangome.views.show_term',
        {'version': settings.DJANGOME['DEFAULT_VERSION']},
    ),
    url('^%s/(?P<term>[\w\-\.]+)$' % ALL_VERSIONS_RE,
        'djangome.views.redirect_to_term',
        name = 'redirect_to_term'
    ),
    url('^%s/(?P<term>[\w\-\.]+)/stats$' % ALL_VERSIONS_RE,
        'djangome.views.show_term',
        name = 'show_term'
    ),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic import RedirectView

ALL_VERSIONS_RE = '(?P<version>%s)' % '|'.join(settings.DJANGOME['VERSIONS'])

urlpatterns = patterns('',
    url('^$',
        RedirectView.as_view(url='http://docs.djangoproject.com/en/dev/')
    ),
    url('^t(?P<n>\d+)$',
        RedirectView.as_view(url='http://code.djangoproject.com/ticket/%(n)s')
    ),
    url('^r(?P<n>\d+)$',
        RedirectView.as_view(url='http://code.djangoproject.com/changeset/%(n)s')
    ),
    url('^__oneoffs__$',
        'djangome.views.manage_oneoffs',
        name = "manage_oneoffs",
    ),
    url('^(?P<term>[\w\-\.]+)$',
        'djangome.views.redirect_to_term',
        {'version': settings.DJANGOME['DEFAULT_VERSION']},
    ),
    url('^(?P<term>[\w\-\.]+)/stats$',
        'djangome.views.show_term',
        {'version': settings.DJANGOME['DEFAULT_VERSION']},
    ),
    url('^%s/(?P<term>[\w\-\.]+)$' % ALL_VERSIONS_RE,
        'djangome.views.redirect_to_term',
        name = 'redirect_to_term'
    ),
    url('^%s/(?P<term>[\w\-\.]+)/stats$' % ALL_VERSIONS_RE,
        'djangome.views.show_term',
        name = 'show_term'
    ),
)

djangome/views.py
import redis
import itertools
import operator
import urlparse
from django import forms
from django import http
from django.conf import settings
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.admin.views.decorators import staff_member_required

r = redis.StrictRedis.from_url(settings.REDIS_URL)

class RedirectForm(forms.Form):
    _domain = 'docs.djangoproject.com'

    url = forms.URLField(label='URL', initial='http://%s/' % _domain)
    title = forms.CharField(label='Title', required=False)

    def clean_url(self):
        url = urlparse.urlparse(self.cleaned_data['url'])
        if url.netloc != self._domain:
            raise forms.ValidationError('Please enter a valid URL starting with http://%s/' % self._domain)
        return self.cleaned_data['url']

def redirect_to_term(request, version, term):
    # Check for an admin oneoff first.
    oneoff_redirect = find_oneoff_redirect(version, term)
    if oneoff_redirect:
        return oneoff_redirect

    form = RedirectForm(request.GET or None)

    # If we're explicitly choosing a new URL for this term, just go ahead and
    # do that. This could also insert new URLs, so do a brief sanity check to
    # make sure this service can't be used for spam.
    if 'url' in request.GET:
        if form.is_valid():
            # Make sure the new URL is in the set of URLs and increment its score.
            url = form.cleaned_data['url']
            r.sadd('redirects:v2:%s:%s' % (version, term), url)
            r.incr('redirects:v2:%s:%s:%s' % (version, term, url))
            return redirect(request.GET.get('return_to', url))

    urls = get_urls(version, term)
    if urls:
        scoregroups = group_urls(urls)

        # The first group is the URLs with the highest score.
        score, winners = scoregroups.next()

        # If there's only a single winning URL, we're done. Count the redirect and
        # then issue it.
        if len(winners) == 1:
            url = winners[0]
            r.incr('redirects:v2:%s:%s:%s' % (version, term, url))
            return redirect(url)

        # Otherwise we need to display a list of all choices. We'll present this into
        # two buckets: the tied URLs with the high score (which is the list of winners
        # we've already gotten) and the tied URLs with a lower score. This second
        # bucket might be empty.
        losers = [losing_group for score, losing_group in scoregroups]

    else:
        winners = losers = None

    return render(request, 'choices.html', {
        'term': term,
        'winners': winners,
        'losers': losers,
        'form': form,
        'version': version,
    })

def show_term(request, version, term):
    user_is_staff = request.user.is_staff
    return render(request, 'show.html', {
        'term': term,
        'version': version,
        'urls': get_urls(version, term),
        'can_edit': user_is_staff,
    })

@csrf_exempt
@staff_member_required
def manage_oneoffs(request):
    """
    Manage the hard-coded one-offs. Admins only.
    """

    if request.method == 'POST':
        if 'action' in request.POST:
            try:
                action, version, term, target = (request.POST['action'],
                                                 request.POST['version'],
                                                 request.POST['term'],
                                                 request.POST['target'])
            except KeyError:
                return redirect(manage_oneoffs)
            if action == 'add':
                add_oneoff(version, term, target)
            elif action == 'kill':
                kill_oneoff(version, term)
        return redirect(manage_oneoffs)

    keys = r.keys('redirects:v2:oneoffs:*')
    targets = r.mget(keys) if keys else []

    oneoffs = []
    for (k, target) in zip(keys, targets):
        k = k.replace('redirects:v2:oneoffs:', '')
        if ':' in k:
            version, term = k.split(':')
        else:
            version, term = None, k
        oneoffs.append((version, term, target))

    return render(request, 'oneoffs.html', {
        'oneoffs': oneoffs,
    })

def find_oneoff_redirect(version, term):
    """
    Find a one-off redirect for the given version/term.

    Returns an HttpResponseRedirect if the redirect was found, None otherwise.

    Increments a count of the found term if successful.
    """
    oneoff_keys = ['redirects:v2:oneoffs:%s' % term,
                   'redirects:v2:oneoffs:%s:%s' % (version, term)]
    oneoff_redirects = r.mget(oneoff_keys)
    for k, target in zip(oneoff_keys, oneoff_redirects):
        if target:
            r.incr('redirects:v2:%s:%s:%s' % (version, term, target))
            return redirect(target)
    return None

def add_oneoff(version, term, target):
    if version:
        k = 'redirects:v2:oneoffs:%s:%s' % (version, term)
    else:
        k = 'redirects:v2:oneoffs:%s' % term
    r.set(k, target)

def kill_oneoff(version, term):
    if version:
        k = 'redirects:v2:oneoffs:%s:%s' % (version, term)
    else:
        k = 'redirects:v2:oneoffs:%s' % term
    print "kill", k
    r.delete(k)

def get_urls(version, term):
    """
    Gets the set of URLs for <term> in <version>.

    Returns a list of (score, url) tuples, sorted by score descending.
    """
    # Sort the set of URLs in redirects:v1:term by the scores (clicks) in
    # redirects:v1:term:url, then get each score along with each URL.
    # This returns a list [score, url, score, url, ...]
    urls = r.sort('redirects:v2:%s:%s' % (version, term),
                  by   = 'redirects:v2:%s:%s:*' % (version, term),
                  get  = ('redirects:v2:%s:%s:*' % (version, term), '#'),
                  desc = True)

    # Convert that to a list of tuples [(score, url), (score, url), ...]
    return zip(urls[::2], urls[1::2])

def group_urls(urls):
    """
    Given a list of (score, url) tuples, group them into buckets by score.

    Returns a list of (score, list_of_urls) tuples.
    """
    for (score, group) in itertools.groupby(urls, operator.itemgetter(0)):
        yield (score, [url for score, url in group])

def firstof(list):
    for i in list:
        if i:
            return i

djangome/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <style type="text/css" media="screen">
    #id_url { width: 80%; }
    p.err { color: red; }
    form { display: inline; }
  </style>
</head>
<body>
  <h1>{% block pagetitle %}{% endblock %}</h1>
  {% block content %}{% endblock %}
</body>

djangome/templates/choices.html
{% extends "base.html" %}

{% block title %}Choose a redirect for "{{ term }}"{% endblock %}
{% block pagetitle %}Choose a redirect for <kbd>{{ term }}</kbd>:{% endblock %}

{% block content %}
  {% load url from future %}
  {% if winners %}
    <ul class="winners">
      {% for choice in winners  %}
        <li><a href="?url={{ choice|urlencode }}">{{ choice }}</a></li>
      {% endfor %}
    </ul>    
  {% endif %}
  {% if losers %}
    <ul class="losers">
      {% for choice in losers %}
        <li><a href="?url={{ choice|urlencode }}">{{ choice }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
  <form action="{% url "redirect_to_term" version=version term=term %}" method="get">
    {% if form.errors %}<p class="err">{{ form.url.errors.as_text }}</p>{% endif %}
    <p>
      {{ form.url.label_tag }}
      {{ form.url }}
      <input type="submit" value="Save &amp; go &rarr;">
    </p>
  </form>
{% endblock %}

djangome/templates/oneoffs.html
{% extends "base.html" %}

{% block title %}One-offs{% endblock %}
{% block pagetitle %}One-offs{% endblock %}

{% block content %}
  {% load url from future %}
  <table>
    <thead>
      <tr>
        <th>Version</th>
        <th>Term</th>
        <th>Target</th>
      </tr>
    </thead>
    <tbody>
      {% for version, term, target in oneoffs %}
        <tr>
          <td><code>{{ version|default:"-" }}</code></td>
          <td><code>{{ term }}</code></td>
          <td><a href="{{ target }}">{{ target }}</a></td>
          <td>
            <form action="{% url "manage_oneoffs" %}" method="post" accept-charset="utf-8">
              <input type="hidden" name="version" value="{{ version|default:"" }}">
              <input type="hidden" name="term" value="{{ term }}">
              <input type="hidden" name="target" value="{{ target }}">
              <input type="submit" name="action" value="kill">
            </form>
          </td>
        </tr>
      {% endfor %}
        <form action="{% url "manage_oneoffs" %}" method="post" accept-charset="utf-8">
          <tr>
            <td><input type="text" name="version" value="" id="version"></td>
            <td><input type="text" name="term" value="" id="term"></td>
            <td><input type="text" name="target" value="" id="target"></td>
            <td><input type="submit" name="action" value="add"></td>
          </tr>
        </form>
    </tbody>
  </table>
{% endblock %}

djangome/templates/show.html
{% extends "base.html" %}

{% block title %}Statistics for "{{ term }}"{% endblock %}
{% block pagetitle %}Statistics for <kbd>{{ term }}</kbd>:{% endblock %}

{% block content %}
  {% load url from future %}
  <table>
    <thead>
      <tr>
        <th>URL</th>
        <th>Clicks</th>
      </tr>
    </thead>
    <tbody>
      {% for score, url in urls %}
        <tr>
          <td>{{ url }}</td>
          <td>
            {{ score }}
            {% if can_edit %}
              <form action="{% url "redirect_to_term" version=version term=term %}" method="get">
                <input type="hidden" name="url" value="{{ url }}">
                <input type="hidden" name="return_to" value="{% url "show_term" version=version term=term %}">
                <input type="submit" name="incr" value="++">
              </form>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      {% if can_edit %}
        <form action="{% url "redirect_to_term" version=version term=term %}" method="get">
          <tr>
            <td>
              <input type="text" name="url" value="http://docs.djangoproject.com/" size="120">
              <input type="hidden" name="return_to" value="{% url "show_term" version=version term=term %}">
            </td>
            <td><input type="submit" value="Add"></td>
          </tr>
        </form>
      {% endif %}
    </tbody>
  </table>
{% endblock %}